app: sle-openorganelle-client-app
service: sle-openorganelle-client

plugins:
  - serverless-finch
  - serverless-deployment-bucket

custom:
  stage: ${opt:stage, self:provider.stage}
  region : ${opt:region, self:provider.region}
  client:
    bucketName: janelia-openorganelle-web-${self:custom.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: max-age=0

provider:
  name: aws
  region: us-east-1
  stage: dev
  deploymentBucket:
    name: janelia-serverless-deployments
    blockPublicAccess: true
  tags:
    PROJECT: cosem
    DEVELOPER: ${env:USER}
    VERSION: ${file(./package.json):version}
