import React from "react";
import { Grid, Typography } from "@mui/material";
import DatasetLayout from "./DatasetLayout";
import NewsPostCarousel from "./NewsPostCarousel";

export default function Home() {
  return (
    <div className="content">
      <Grid container spacing={2}>
        <Grid item>
          <NewsPostCarousel />
        </Grid>
        <Grid item>
          <DatasetLayout latestOnly />
        </Grid>
        <Grid item>
          <Typography
            variant="h3"
            gutterBottom
            style={{ marginTop: "2em", textAlign: "center" }}
          >
            Welcome to HHMI Janelia’s OpenOrganelle.
          </Typography>
          <p style={{ textIndent: "3ch" }}>
            On this data portal we present high resolution tissue-scale volume
            electron microscopy (vEM) datasets acquired with the enhanced
            focused ion beam scanning electron microscopy (FIB-SEM) technology
            developed at Janelia. Accompanying these EM volumes are automated
            segmentations and analyses of intracellular sub-structures.
          </p>

          <p style={{ textIndent: "3ch" }}>
            Within Janelia are some of the world’s leading research groups in
            Machine Learning (
            <a href="https://www.janelia.org/lab/saalfeld-lab">Saalfeld lab</a>{" "}
            and <a href="https://www.janelia.org/lab/funke-lab">Funke lab</a>),
            Cell Biology (
            <a href="https://www.janelia.org/lab/lippincott-schwartz-lab">
              Lippincott-Schwartz lab
            </a>
            ), and large-volume, high-resolution EM data acquisition (
            <a href="https://www.janelia.org/project-team/fib-sem-technology">
              FIB-SEM Technology
            </a>{" "}
            and <a href="https://www.janelia.org/lab/hess-lab">Hess lab</a>
            ). This provides a unique opportunity to expand research at the
            intersection of these fields and drive forward our tools to study
            subcellular structures; this effort is being led by the{" "}
            <a href="https://www.janelia.org/project-team/cosem">
              COSEM Project Team
            </a>
            .
          </p>

          <p style={{ textIndent: "3ch" }}>
            The unprecedented volume and resolution of vEM datasets generated by
            the enhanced FIB-SEM platform (Hess Lab and FIB-SEM Technology) both
            demands and enables the development of universal machine learning
            classifiers for the automatic detection of sub-cellular structures
            in these data. The COSEM project team, in collaboration with the
            Saalfeld and Funke labs with biological guidance from the
            Lippincott-Schwartz lab, has begun tackling the segmentation problem
            as well as the subsequent large-scale quantitative analysis of these
            data to answer biological questions.
          </p>

          <p style={{ textIndent: "3ch" }}>
            On this site you will find all datasets, training data and
            segmentations available for exploration. Be sure to also check out
            our tutorials to learn how to work with the data yourself and our
            publications list to learn more!
          </p>
        </Grid>
      </Grid>
    </div>
  );
}
